" Colorscheme
syntax on
let &background = $THEME_MODE
set notermguicolors
colorscheme memono

" Indentation
set shiftwidth=4
set expandtab
set smarttab
set softtabstop=4
set tabstop=4

" Options
set autoindent
set autoread
set clipboard=unnamed,unnamedplus
set colorcolumn=80
set cursorline
set grepformat=%f:%l:%c:%m
set grepprg=rg\ --vimgrep
set hidden
set hlsearch
set incsearch
set laststatus=2
set makeprg=
set noswapfile
set ruler
set scrolloff=8
set smartcase
set ttimeout
set ttimeoutlen=50
set wildmenu
set wildoptions=pum,tagfile
